function missionData = missionParameters()
% Create a dictionary for satellite altimetry missions
missionData = dictionary;

missionData('al') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/saral/orbit-1.html', ...
    'name', 'Saral/AltiKa 35-day orbit', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('14-Mar-2013 05:44:50')], ...
    'end_date', [datetime('31-Mar-2015 22:41:26')], ...
    'semi-major-axis', 7159.496, ...
    'eccentricity', 0.000165, ...
    'inclination', 98.55, ...
    'orbits-per-cycle', 501, ...
    'repeat-cycle', 35.0, ...
    'is-reference-mission', false ...
);

missionData('alg') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/saral/orbit-1.html', ...
    'name', 'Saral/AltiKa drifting (geodetic) orbit', ...
    'description','Decaying orbit, no repeat cycle', ...
    'start_date', [datetime('31-Mar-2015 22:53:34')], ...
    'end_date', [datetime('308-Sep-2023 22:47:46')], ...
    'semi-major-axis', 8000.496, ...
    'eccentricity', 0, ...
    'inclination', 98.55, ...
    'orbits-per-cycle', Inf, ...
    'repeat-cycle', Inf, ...
    'is-reference-mission', false ...
);

missionData('c2') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/cryosat.html', ...
    'name', 'Cryosat-2', ...
    'description','Non-repeating orbit', ...
    'start_date', [datetime('16-Jul-2010 00:22:02')], ...
    'end_date', [datetime('31-Jul-2020 11:29:44')], ...
    'semi-major-axis', 6378 + 717, ...
    'eccentricity', 0, ...
    'inclination', 92.03, ...
    'repeat-cycle', Inf, ...
    'is-reference-mission', false ...
);

missionData('c2n') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/cryosat.html', ...
    'name', 'Cryosat-2 new orbit', ...
    'description','Non-repeating orbit. New orbit, but not sure how it differs from previous', ...
    'start_date', [datetime('01-Aug-2020 10:56:11')], ...
    'end_date', [datetime('08-Sep-2023 23:14:41')], ...
    'semi-major-axis', 6378 + 717, ...
    'eccentricity', 0, ...
    'inclination', 92.03, ...
    'repeat-cycle', Inf, ...
    'is-reference-mission', false ...
);

missionData('e1') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-1.html', ...
    'name', 'ERS-1 35-day orbit', ...
    'start_date', [datetime('23-Oct-1992 22:14:26'), datetime('24-Mar-1995 02:11:31')], ...
    'end_date', [datetime('20-Dec-1993 11:28:02'), datetime('15-May-1995 20:38:41')], ...
    'semi-major-axis', 7159.496*[1 1], ...
    'eccentricity', 0.0001042, ...
    'inclination', 98.543*[1 1], ...
    'orbits-per-cycle', 501, ...
    'repeat-cycle', 35.0, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);

missionData('e1g') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-1.html', ...
    'name', 'ERS-1 168-day geodetic orbit', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('10-Apr-1994 18:20:38')], ...
    'end_date', [datetime('21-Mar-1995 05:40:47')], ...
    'semi-major-axis', 7147.191, ...
    'inclination', 98.491, ...
    'orbits-per-cycle', 2411, ...
    'repeat-cycle', 168.0, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 168-day orbit' ...
);

missionData('e2') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-2.html', ...
    'name', 'ERS-2 35-day orbit', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('15-May-1995 22:11:19')], ...
    'end_date', [datetime('14-May-2002 18:04:55')], ...
    'semi-major-axis', 7159.5, ...
    'eccentricity', 0.0001042, ...
    'inclination', 98.543, ...
    'orbits-per-cycle', 501, ...
    'repeat-cycle', 35.0, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);

missionData('en') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/envisat/orbit.html', ...
    'name', 'Envisat 35-day orbit', ...
    'start_date', [datetime('17-May-2002 07:23:51')], ...
    'end_date', [datetime('18-Oct-2010 21:26:41')], ...
    'semi-major-axis', 7159.5, ...
    'eccentricity', 0.001165, ...
    'inclination', 98.55, ...
    'orbits-per-cycle', 501, ...
    'repeat-cycle', 35.0, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);

missionData('enn') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/envisat/orbit.html', ...
    'name', 'Envisat 30-day orbit', ...
    'start_date', [datetime('26-Oct-2010 07:58:16')], ...
    'end_date', [datetime('08-Apr-2012 10:43:05')], ...
    'semi-major-axis', 7142.0, ...
    'eccentricity', 0.001158, ...
    'inclination', 98.55, ...
    'orbits-per-cycle', 431, ...
    'repeat-cycle', 30.0, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 30-day orbit' ...
);

missionData('tp') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/topex-poseidon/orbits.html', ...
    'name', 'TOPEX/Poseidon', ...
    'start_date', [datetime('03-Oct-1992 01:42:25')], ...
    'end_date', [datetime('24-Apr-2002 07:56:09')], ...
    'semi-major-axis', 7714.4278, ...
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...
    'orbits-per-cycle', 254, ...
    'longitude-at-equator-pass-1', deg2rad(98.51), ...
    'repeat-cycle', 9.9156, ...
    'is-reference-mission', true, ...
    'OrbitTypeNotes', 'Joint NASA/CNES mission ("reference" mission)' ...
);

missionData('tpn') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/topex-poseidon/orbits.html', ...
    'name', 'TOPEX/Poseidon', ...
    'start_date', [datetime('20-Sep-2002 02:46:40')], ...
    'end_date', [datetime('08-Oct-2005 23:49:29')], ...
    'semi-major-axis', 7714.4278, ...
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...
    'orbits-per-cycle', 254, ...
    'longitude-at-equator-pass-1', deg2rad(99.9242), ...
    'repeat-cycle', 9.9156, ...
    'is-reference-mission', false, ...
    'OrbitTypeNotes', 'Joint NASA/CNES mission ("reference" mission)' ...
);

% Jason-1
missionData('Jason-1') = struct( ...
    'LaunchDate', '2001-12-07', ...
    'EndDate', '2013-07-10', ...
    'altitude', 1336, ...   % nearly circular orbit
    'inclination', 66, ...
    'OrbitTypeNotes', 'Follow-on to TOPEX/Poseidon (Jason series)' ...
);

% Envisat
missionData('Envisat') = struct( ...
    'LaunchDate', '2002-03-01', ...
    'EndDate', '2012-04-08', ...
    'altitude', 790, ...
    'inclination', 98.6, ...
    'OrbitTypeNotes', 'ESA multi-instrument mission including altimetry (RA-2)' ...
);

% Jason-2 (OSTM/Jason-2)
missionData('Jason-2') = struct( ...
    'LaunchDate', '2008-06-07', ...
    'EndDate', '~2019', ...
    'altitude', 1336, ...
    'inclination', 66, ...
    'OrbitTypeNotes', 'Continued the Jason series' ...
);

% CryoSat-2
missionData('CryoSat-2') = struct( ...
    'LaunchDate', '2010-04-08', ...
    'EndDate', 'Operational (extended)', ...
    'altitude', 720, ...  % Mean altitude (~679-737 km)
    'inclination', 92, ...
    'OrbitTypeNotes', 'Designed for ice/cryospheric studies; near-polar orbit' ...
);

% HY-2A
missionData('HY-2A') = struct( ...
    'LaunchDate', '2008-10-06', ...
    'EndDate', 'Operational?', ...
    'altitude', 891, ...
    'inclination', 98.3, ...
    'OrbitTypeNotes', 'Chinese altimetry mission (oceanography)' ...
);

% SARAL/AltiKa
missionData('SARAL/AltiKa') = struct( ...
    'LaunchDate', '2013-02-25', ...
    'EndDate', 'Operational', ...
    'altitude', 1336, ...   % nearly circular orbit
    'inclination', 66, ...
    'OrbitTypeNotes', 'Joint ISRO–CNES mission; similar orbit to Jason series' ...
);

% Jason-3
missionData('Jason-3') = struct( ...
    'LaunchDate', '2016-01-17', ...
    'EndDate', 'Operational', ...
    'altitude', 1336, ...   % nearly circular orbit
    'inclination', 66, ...
    'OrbitTypeNotes', 'Latest in the Jason series' ...
);

% Sentinel-3A
missionData('Sentinel-3A') = struct( ...
    'LaunchDate', '2016-02-16', ...
    'EndDate', 'Operational', ...
    'altitude', 814, ...
    'inclination', 98.6, ...
    'OrbitTypeNotes', 'ESA ocean and land monitoring; sun-synchronous' ...
);

% Sentinel-3B
missionData('Sentinel-3B') = struct( ...
    'LaunchDate', '2018-04-04', ...
    'EndDate', 'Operational', ...
    'altitude', 814, ...
    'inclination', 98.6, ...
    'OrbitTypeNotes', 'ESA companion to Sentinel-3A' ...
);

% HY-2B
missionData('HY-2B') = struct( ...
    'LaunchDate', '~2012?', ...
    'EndDate', 'Operational?', ...
    'altitude', 891, ...
    'inclination', 98.3, ...
    'OrbitTypeNotes', 'Follow-on to HY-2A' ...
);

end